#include "header.h"
void Inventory (ostream &file)
{
	file << "                    Sloppy Disks Inc\n"
			"********************************************************************************************\n"
			"123 Cool Street\n"
			"Coolsvile, California 92652\n"
			"(949) 555-5555\n"
			"customersupport@sdi.com\n\n"
			"About Us:\n"
			"********************************************************************************************\n"
			"Slopp Disks Inc (SDinc) was founded by Dori Mouawad, Josh Montgomery,\n"
			"Talon Baker, and James Davis in 2014. SDinc specializes in the \n"
			"produciton and sale of top-of-the-line bomb disposal robots. It is\n"
			"our goal here at SDinc to provide our customers with the best products\n"
			"and service possible. You'll love our Bots, or your money back!\n\n"
			"Our Products:\n"
			"********************************************************************************************\n"
			"\nEARTH-BOT\n"
			"Our corner stone model. The Earth-Bot is a ground based, bomb disposing\n"
			"beast. Whether it be high desert or jungle terrain, the Earth Bot comes\n"
			"standard or with upgrades.\n"
			"\nUpgrades Available: iOS controller, Android controller, 4x4 drive train,\n"
			"                    super charged engine.\n\n"
			"\nAIR-BOT\n"
			"The Air Bot utilizes the latest in aerospace engineering and drone technology\n"
			"to bring you the best in aerial bomb disposal. Never again will those bombs in\n"
			"hard-to-reach places give you trouble. The Air Bot can ascend, descend, and hover\n"
			"with the utmost precision.\n"
			"\nUpgrades Available: iOS controller, Android controller, high altitude capabilities,\n"
			"                    auto-pilot.\n\n"
			"\nSEA-BOT\n"
			"The Sea Bot is a first of its kind. first developed for the US Navy to dispose of\n"
			"mines, the Sea Bot has been perfected for everday use! Got a bomb in the river? No\n"
			"problem. Bomb in the ocean? No problem. Bomb in your backyard pool? No problem! Whether\n"
			"it be fresh water, salt water, or bath water, the Sea Bot will make it so you don't worry\n"
			"about being blown up on your weekend yacht trip.\n"
			"\nUpgrades Available: iOS controller, Android controller, sonar, submarine capability.\n\n";
}
